### PR TITLE
Error Detection Tutorials v1

### PR DESCRIPTION
**Pull request by jw-mcgrath**
I did two things on this branch

1. Cleaned up the `ErrorDetector` class in order to make it more general, and allow users to more easily create their own error detectors
2. Created a simple tutorial showing users how to create their own error detctors

Please note that we'll need to change some of our existing tutorials to match the new error detection scheme, but this was required anyway. @JVonderwell @gmichalo @j48zheng Should we update tutorials on this branch, or create a new issue to refactor tutorials?

### CODE REVIEW

**Review by j48zheng — COMMENTED** [review]
For the last displayed table, do we need to show all the rows from 1-45, can we not just show index 45?

**Comment by jw-mcgrath** [comment]
@j48zheng I haven't used spark a ton, do you know what function I would use to do that?

**Review by gmichalo — CHANGES_REQUESTED** [review]
You can use this command just to show the row with index 45:
sql.filter(sql.index == 45).select(["index","ZipCode"]).show()

**Review by gmichalo — COMMENTED** [review]
In cells 2-3 we could have a small description of the code or we can point to the other tutorials that we have where we describe the creation of holoclean session and how we are ingesting a file

**Review by gmichalo — APPROVED** [review]

**Review by thodrek — APPROVED** [review]

**Pull request merged**
